apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-tag
spec:
  params:
    - name: git-user-name
      description: Name to use for git commits
      default: tekton-bot
    - name: git-user-email
      description: Email to use for git commits
      default: tekton@example.com
  workspaces:
    - name: source
      description: Workspace with the cloned git repository
  results:
    - name: image-tag
      description: Generated semantic version tag
  steps:
    - name: generate
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        # Prefer short SHA + UTC timestamp to avoid needing git push
        if git rev-parse --short HEAD >/dev/null 2>&1; then
          SHORT_SHA=$(git rev-parse --short HEAD)
        else
          SHORT_SHA=unknown
        fi
        STAMP=$(date -u +%Y%m%d%H%M%S)
        NEW_TAG="sha-${SHORT_SHA}-${STAMP}"
        printf "%s" "$NEW_TAG" > $(results.image-tag.path)
