# Registry chart default values

nameOverride: "registry"
fullnameOverride: "registry"

replicaCount: 1

image:
  repository: registry
  tag: "2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: 30050

persistence:
  enabled: true
  existingClaim: ""
  storageClass: "standard"
  size: 20Gi

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 256Mi
  # requests:
  #   cpu: 50m
  #   memory: 128Mi

podLabels: {}

nodeSelector: {}

tolerations: []

affinity: {}

probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
