# Monitoring Stack Values for eBPF-AI Platform

global:
  namespace: monitoring

# Prometheus Configuration
prometheus:
  enabled: true
  alertmanager:
    enabled: true
    persistentVolume:
      enabled: true
      size: 2Gi
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
    service:
      type: ClusterIP
      port: 9090
    retention: "30d"
    
    # Custom scrape configs for eBPF-AI
    extraScrapeConfigs: |
      - job_name: 'ebpf-monitor'
        static_configs:
        - targets: ['ebpf-monitor.ebpf-security.svc.cluster.local:8800']
        metrics_path: /metrics
        scrape_interval: 15s
      - job_name: 'ml-detector'
        static_configs:  
        - targets: ['ml-detector.ebpf-security.svc.cluster.local:5000']
        metrics_path: /metrics
        scrape_interval: 15s

# Grafana Configuration  
grafana:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: admin123
  
  # Plugins for enhanced visualizations
  plugins:
    - grafana-piechart-panel
    - grafana-worldmap-panel
    - grafana-polystat-panel
    
  # Datasources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local:9090
          access: proxy
          isDefault: true
          
  # Import custom dashboards
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'ebpf-ai-dashboards'
        orgId: 1
        folder: 'eBPF-AI'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/ebpf-ai
          
  dashboards:
    ebpf-ai:
      ebpf-network-monitoring:
        url: https://raw.githubusercontent.com/jeanlopezxyz/ebpf-ia-gitops/main/monitoring/dashboards/ebpf-network.json
      ml-threat-detection:
        url: https://raw.githubusercontent.com/jeanlopezxyz/ebpf-ia-gitops/main/monitoring/dashboards/ml-detection.json