# pipelineRuns enabled by default
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ebpf-monitor-build-
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: tekton-ci
    app.kubernetes.io/instance: tekton-ci
    app.kubernetes.io/component: pipelinerun-ebpf-monitor
    app.kubernetes.io/part-of: ebpf-ai-system
spec:
  pipelineRef:
    name: simple-ci
  taskRunTemplate:
    serviceAccountName: pipeline-sa
    podTemplate:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: git-url
      value: https://github.com/jeanlopezxyz/ebpf-ia-gitops.git
    - name: git-revision
      value: main
    - name: image-registry
      value: registry.container-registry.svc.cluster.local:5000
    - name: image-name
      value: ebpf-monitor
    - name: dockerfile-path
      value: ./applications/ebpf-monitor/Dockerfile
    - name: context-path
      value: ./applications/ebpf-monitor

