apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc
  annotations:
    # Additional storage class for fsGroup compatibility
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: ebpf-ai-platform
provisioner: hostpath.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  # CSI hostpath specific parameters for fsGroup support
  fsType: ext4