---
# NetworkPolicy to allow ebpf-security namespace to access registry
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ebpf-security-to-registry
  namespace: registry
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ebpf-security
    ports:
    - protocol: TCP
      port: 5000
  - from:
    - namespaceSelector:
        matchLabels:
          name: tekton
    ports:
    - protocol: TCP
      port: 5000
  - from: []  # Allow all other traffic (for health checks, etc.)
    ports:
    - protocol: TCP
      port: 5000
---
# Ensure ebpf-security namespace has the required label
apiVersion: v1
kind: Namespace
metadata:
  name: ebpf-security
  labels:
    name: ebpf-security
    app.kubernetes.io/part-of: ebpf-ai-system
---
# Ensure tekton namespace has the required label  
apiVersion: v1
kind: Namespace
metadata:
  name: tekton
  labels:
    name: tekton
    app.kubernetes.io/part-of: tekton-system