---
# NetworkPolicy to allow all namespaces to access registry (development mode)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-to-registry
  namespace: registry
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - {}  # Allow all traffic to registry pods
# Note: ebpf-security namespace is managed by ebpf-ai application
# We only add the NetworkPolicy, not manage the namespace
# Note: tekton namespace is managed by tekton application
# We only add the NetworkPolicy, not create the namespace