apiVersion: v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    # Remove default annotation from standard storage class
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false