apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: ebpf-ai-system
    app.kubernetes.io/component: argocd-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.0
    helm:
      values: |
        # Simple Grafana-only deployment
        adminPassword: admin123
        service:
          type: NodePort
        persistence:
          enabled: false
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            searchNamespace: true
        grafana.ini:
          server:
            root_url: http://localhost:3000
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.local
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
