apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: ebpf-ai-platform
    app.kubernetes.io/component: ingress-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.11.3"
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: controller.service.type
          value: "LoadBalancer"
        - name: controller.service.loadBalancerIP
          value: "10.0.10.110"  # Fixed IP for all apps
        - name: controller.service.annotations.metallb\.universe\.tf/address-pool
          value: "nginx-pool"  # Use dedicated pool
        - name: controller.service.externalTrafficPolicy
          value: "Local"
        - name: controller.ingressClassResource.default
          value: "true"
        - name: controller.metrics.enabled
          value: "true"
        - name: controller.podAnnotations.prometheus\.io/scrape
          value: "true"
        - name: controller.podAnnotations.prometheus\.io/port
          value: "10254"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10