apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-namespace
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton-namespace
    app.kubernetes.io/part-of: ebpf-ai-platform
    app.kubernetes.io/component: tekton-namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before other Tekton apps
spec:
  project: default
  source:
    repoURL: https://github.com/jeanlopezxyz/ebpf-ia-gitops.git
    targetRevision: main
    path: gitops/tekton-namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10