apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton-pipelines
    app.kubernetes.io/part-of: ebpf-ai-platform
    app.kubernetes.io/component: tekton-core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cdfoundation.github.io/tekton-helm-chart
    chart: tekton-pipeline
    targetRevision: 1.2.0
    helm:
      parameters:
        - name: controller.resources.requests.cpu
          value: "100m"
        - name: controller.resources.requests.memory
          value: "256Mi"
        - name: createNamespace
          value: "true"
        - name: namespace.podSecurityEnforce
          value: "privileged"
        - name: set-security-context
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - NamespaceMetadata={"labels":{"pod-security.kubernetes.io/enforce":"privileged"}}
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
