apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-ci-pipelines
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton-ci-pipelines
    app.kubernetes.io/part-of: ebpf-ai-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jeanlopezxyz/ebpf-ia-gitops.git
    targetRevision: main
    path: tekton/pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: ebpf-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10