namespaceOverride: ""

# Where to push images built by pipelines
imageRegistry: "registry.container-registry.svc.cluster.local:5000"

# Target Argo CD Application to sync after build
argoAppName: "ebpf-ai"

# Control creating PipelineRuns on install
pipelineRuns:
  enabled: true
