# MetalLB Configuration for eBPF-AI Platform

metallb:
  # Use official MetalLB chart
  enabled: true
  
# IP Address Pool Configuration
ipAddressPools:
  # Reserved pool for NGINX Ingress Controller
  - name: "nginx-pool"
    addresses:
      - "10.0.10.101/32"  # Single IP reserved for NGINX
  # General pool for other LoadBalancers
  - name: "apps-pool"
    addresses:
      - "10.0.10.102-10.0.10.120"  # 19 IPs for other applications

# L2 Advertisement Configuration  
l2Advertisement:
  name: "apps-l2"
  ipAddressPools:
    - "apps-pool"
  interfaces:
    - "br0"  # Bridge interface
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: "labjp"