apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ebpf-monitor-ci
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: ebpf-monitor-ci
    app.kubernetes.io/part-of: ebpf-ai-system
spec:
  description: CI pipeline for eBPF Monitor application
  params:
    - name: git-url
      description: Git repository URL
      default: https://github.com/jeanlopezxyz/ebpf-ia-gitops.git
    - name: git-revision
      description: Git revision to build
      default: main
    - name: image-registry
      description: Container registry URL
      default: 192.168.67.2:5000
    - name: image-name
      description: Image name
      default: ebpf-monitor
    - name: image-tag
      description: Image tag
      default: latest
      
  workspaces:
    - name: shared-data
      description: Shared workspace for source code
      
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: Task
        apiVersion: tekton.dev/v1
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
          
    - name: build-image
      taskRef:
        name: buildah
        kind: Task
        apiVersion: tekton.dev/v1
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.image-registry)/$(params.image-name):$(params.image-tag)
        - name: DOCKERFILE
          value: ./applications/ebpf-monitor/Dockerfile
        - name: CONTEXT
          value: ./applications/ebpf-monitor
        - name: TLSVERIFY
          value: "false"