{{- if .Values.ebpfMonitor.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ebpf-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: ebpf-monitor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebpf-monitor
  labels:
    {{- include "ebpf-ai.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebpf-monitor
  labels:
    {{- include "ebpf-ai.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebpf-monitor
subjects:
- kind: ServiceAccount
  name: ebpf-monitor
  namespace: {{ .Release.Namespace }}

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ebpf-monitor
  labels:
    {{- include "ebpf-ai.labels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  requiredDropCapabilities: []
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  allowedCapabilities:
  - CAP_BPF
  - CAP_NET_ADMIN
  - CAP_NET_RAW
  - CAP_SYS_ADMIN
  - CAP_PERFMON
  - CAP_SYS_RESOURCE

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ebpf-monitor-psp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ebpf-ai.labels" . | nindent 4 }}
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["ebpf-monitor"]
  verbs: ["use"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ebpf-monitor-psp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ebpf-ai.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ebpf-monitor-psp
subjects:
- kind: ServiceAccount
  name: ebpf-monitor
  namespace: {{ .Release.Namespace }}
{{- end }}