apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  {{- range .Values.ipAddressPool.addresses }}
  - {{ . }}
  {{- end }}