{{- range .Values.ipAddressPools }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  addresses:
  {{- range .addresses }}
  - {{ . }}
  {{- end }}
---
{{- end }}