{{- range .Values.l2Advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ipAddressPools:
  {{- range .ipAddressPools }}
  - {{ . }}
  {{- end }}
  {{- if .interfaces }}
  interfaces:
  {{- range .interfaces }}
  - {{ . }}
  {{- end }}
  {{- end }}
  {{- if .nodeSelectors }}
  nodeSelectors:
  {{- toYaml .nodeSelectors | nindent 2 }}
  {{- end }}
---
{{- end }}