apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2Advertisement.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  {{- range .Values.l2Advertisement.ipAddressPools }}
  - {{ . }}
  {{- end }}
  {{- if .Values.l2Advertisement.interfaces }}
  interfaces:
  {{- range .Values.l2Advertisement.interfaces }}
  - {{ . }}
  {{- end }}
  {{- end }}
  {{- if .Values.l2Advertisement.nodeSelectors }}
  nodeSelectors:
  {{- toYaml .Values.l2Advertisement.nodeSelectors | nindent 2 }}
  {{- end }}