apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-semantic-tag
  namespace: {{ .Release.Namespace }}
spec:
  description: Generate semantic version tag (v1.0, v1.1, etc.)
  params:
    - name: app-name
      description: Application name (ml-detector or ebpf-monitor)
      type: string
  results:
    - name: image-tag
      description: Generated semantic version tag
    - name: version
      description: Version number without 'v' prefix
  workspaces:
    - name: source
  steps:
    - name: generate-version
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        
        # Get the latest tag for this application
        APP_NAME=$(params.app-name)
        
        # Initialize git config for tagging (local only)
        git config user.email "tekton@ebpf-ai.local"
        git config user.name "Tekton Pipeline"
        
        # Fetch all tags
        git fetch --tags || true
        
        # Get the latest version tag for this app
        LATEST_TAG=$(git tag -l "v*-${APP_NAME}" | sort -V | tail -n 1)
        
        if [ -z "$LATEST_TAG" ]; then
          # No previous tags, start with v1.0
          NEW_VERSION="1.0"
        else
          # Extract version number and increment
          VERSION=$(echo $LATEST_TAG | sed "s/v\(.*\)-${APP_NAME}/\1/")
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          
          # Increment minor version
          MINOR=$((MINOR + 1))
          NEW_VERSION="${MAJOR}.${MINOR}"
        fi
        
        # Create the new tag
        NEW_TAG="v${NEW_VERSION}-${APP_NAME}"
        
        # Save results
        echo "$NEW_TAG" > $(results.image-tag.path)
        echo "$NEW_VERSION" > $(results.version.path)
        
        echo "Generated tag: $NEW_TAG"