apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-tag-push
  namespace: {{ .Release.Namespace }}
spec:
  description: Push git tag to repository
  params:
    - name: tag
      description: Tag to push
      type: string
    - name: git-url
      description: Git repository URL
      type: string
      default: https://github.com/jeanlopezxyz/ebpf-ia-gitops.git
  workspaces:
    - name: source
    - name: git-credentials
      optional: true
  steps:
    - name: push-tag
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: token
              optional: true
      script: |
        #!/usr/bin/env sh
        set -eu
        
        TAG=$(params.tag)
        
        # Configure git
        git config --global user.email "tekton@ebpf-ai.local"
        git config --global user.name "Tekton Pipeline"
        
        # Create the tag locally
        git tag -a "$TAG" -m "Release $TAG - Generated by Tekton CI"
        
        # Try to push the tag (will fail if no credentials, but that's ok for now)
        if [ ! -z "${GIT_TOKEN:-}" ]; then
          # Configure git to use token
          git remote set-url origin https://${GIT_TOKEN}@github.com/jeanlopezxyz/ebpf-ia-gitops.git
          git push origin "$TAG"
          echo "Tag $TAG pushed to repository"
        else
          echo "Warning: No git credentials, tag created locally only"
        fi