apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-deployment-tag
  namespace: {{ .Release.Namespace }}
spec:
  description: Update deployment configuration with new image tag
  params:
    - name: app-name
      description: Application name (ml-detector or ebpf-monitor)
      type: string
    - name: new-tag
      description: New image tag to use
      type: string
    - name: git-url
      description: Git repository URL
      type: string
      default: https://github.com/jeanlopezxyz/ebpf-ia-gitops.git
  workspaces:
    - name: source
    - name: git-credentials
      optional: true
  steps:
    - name: update-and-commit
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: token
              optional: true
      script: |
        #!/usr/bin/env sh
        set -eu
        
        APP_NAME=$(params.app-name)
        NEW_TAG=$(params.new-tag)
        
        # Configure git (local only)
        git config user.email "tekton@ebpf-ai.local"
        git config user.name "Tekton Pipeline"
        
        # Update the ArgoCD application yaml
        ARGO_FILE="gitops/applications/ebpf-ai-app.yaml"
        
        if [ "$APP_NAME" = "ml-detector" ]; then
          # Update ml-detector tag
          sed -i "s/name: mlDetector.image.tag/name: mlDetector.image.tag/,/value:/{s/value: .*/value: \"$NEW_TAG\"/}" $ARGO_FILE
        elif [ "$APP_NAME" = "ebpf-monitor" ]; then
          # Update ebpf-monitor tag
          sed -i "s/name: ebpfMonitor.image.tag/name: ebpfMonitor.image.tag/,/value:/{s/value: .*/value: \"$NEW_TAG\"/}" $ARGO_FILE
        fi
        
        # Also update values.yaml as backup
        VALUES_FILE="helm/charts/ebpf-ai/values.yaml"
        if [ "$APP_NAME" = "ml-detector" ]; then
          sed -i "s/tag: .*/tag: $NEW_TAG/" $VALUES_FILE | head -15
        elif [ "$APP_NAME" = "ebpf-monitor" ]; then
          sed -i "s/tag: .*/tag: $NEW_TAG/" $VALUES_FILE | tail -20 | head -10
        fi
        
        # Commit changes
        git add $ARGO_FILE $VALUES_FILE || true
        git diff --staged --quiet || {
          git commit -m "Update $APP_NAME to version $NEW_TAG
        
        Generated by Tekton CI Pipeline
        [skip ci]"
        
          # Push changes if we have credentials
          if [ ! -z "${GIT_TOKEN:-}" ]; then
            git remote set-url origin https://${GIT_TOKEN}@github.com/jeanlopezxyz/ebpf-ia-gitops.git
            git push origin main
            echo "Changes pushed to repository"
          else
            echo "Warning: No git credentials, changes committed locally only"
          fi
        }
        
        echo "Deployment configuration updated with tag: $NEW_TAG"