---
- name: Add Prometheus Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    
- name: Add Grafana Helm repository
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
    
- name: Install Prometheus Operator CRDs
  kubernetes.core.helm:
    name: prometheus-operator-crds
    chart_ref: prometheus-community/prometheus-operator-crds
    release_namespace: monitoring
    create_namespace: true
    wait: false
    
- name: Install kube-prometheus-stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    values:
      prometheus:
        prometheusSpec:
          # Use emptyDir to avoid hostPath issues in Minikube
          storageSpec: {}
          additionalScrapeConfigs:
            - job_name: 'ml-detector'
              static_configs:
                - targets: ['ml-detector.ebpf-security.svc.cluster.local:5000']
              metrics_path: '/metrics'
              scrape_interval: 30s
            - job_name: 'ebpf-monitor'
              static_configs:
                - targets: ['ebpf-monitor.ebpf-security.svc.cluster.local:8800']
              metrics_path: '/metrics'
              scrape_interval: 15s
          serviceMonitorSelectorNilUsesHelmValues: false
          ruleSelectorNilUsesHelmValues: false
      grafana:
        enabled: true
        adminPassword: admin123
        service:
          type: "{{ 'LoadBalancer' if deployment_mode.type == 'prod' else 'NodePort' }}"
        persistence:
          enabled: false
        plugins:
          - grafana-piechart-panel
          - grafana-worldmap-panel
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'ebpf-ai'
                orgId: 1
                folder: 'eBPF + AI'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/ebpf-ai
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            folder: /tmp/dashboards
            provider:
              foldersFromFilesStructure: true
      alertmanager:
        enabled: false  # Disable to avoid hostPath issues in Minikube
    wait: false
    
- name: Wait for Prometheus pods to be running (simple validation)
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app.kubernetes.io/name=prometheus
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
    
- name: Create Grafana Ingress for UI access
  kubernetes.core.k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: grafana-ingress
        namespace: monitoring
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
      spec:
        ingressClassName: nginx
        rules:
        - host: grafana.local
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: kube-prometheus-stack-grafana
                  port:
                    number: 80
        - http:
            paths:
            - path: /grafana
              pathType: Prefix
              backend:
                service:
                  name: kube-prometheus-stack-grafana
                  port:
                    number: 80
    state: present

- name: Get Grafana service information
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: kube-prometheus-stack-grafana
    namespace: monitoring
  register: grafana_service
  
- name: Display monitoring stack information
  debug:
    msg:
      - "📊 Prometheus + Grafana stack installation completed!"
      - "🎯 Prometheus: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      - "📈 Grafana: {{ grafana_service.resources[0].status.loadBalancer.ingress[0].ip | default('Service starting...') if grafana_service.resources is defined else 'Service starting...' }}"
      - "👤 Grafana Login: admin / admin123"
      - "🔔 AlertManager: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093"
      - "💡 Port forward Grafana: kubectl port-forward svc/kube-prometheus-stack-grafana -n monitoring 3000:80"
      - "⏳ Note: Services may take a few minutes to be fully ready"