apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: registry-global-access
spec:
  description: "Allow all namespaces to access the container registry"
  endpointSelector:
    matchLabels:
      "k8s:io.kubernetes.pod.namespace": registry
      "k8s:app.kubernetes.io/name": registry
  ingress:
    - fromEndpoints:
      - {}  # Allow from any pod in any namespace
      toPorts:
      - ports:
        - port: "5000"
          protocol: TCP
---
# Also ensure DNS is allowed for registry resolution
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-cluster-dns
spec:
  description: "Allow all pods to access kube-dns/coredns"
  endpointSelector: {}
  egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
    - toServices:
      - k8sService:
          serviceName: kube-dns
          namespace: kube-system
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP