{{- if .Values.tls.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "registry.fullname" . }}-ca-installer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: ca-installer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "registry.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ca-installer
  template:
    metadata:
      labels:
        {{- include "registry.labels" . | nindent 8 }}
        app.kubernetes.io/component: ca-installer
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: ca-installer
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          # Create directories and install CA certificate for Docker
          mkdir -p /host/etc/docker/certs.d/registry.container-registry.svc.cluster.local:5000
          mkdir -p /host/etc/docker/certs.d/10.100.86.194:5000
          mkdir -p /host/etc/docker/certs.d/192.168.67.2:5000
          mkdir -p /host/etc/containerd/certs.d/registry.container-registry.svc.cluster.local:5000
          
          # Copy CA certificates
          cp /ca/ca.crt /host/etc/docker/certs.d/registry.container-registry.svc.cluster.local:5000/ca.crt
          cp /ca/ca.crt /host/etc/docker/certs.d/10.100.86.194:5000/ca.crt
          cp /ca/ca.crt /host/etc/docker/certs.d/192.168.67.2:5000/ca.crt
          cp /ca/ca.crt /host/etc/containerd/certs.d/registry.container-registry.svc.cluster.local:5000/ca.crt
          
          echo "CA certificates installed successfully"
          # Keep pod running
          sleep infinity
        volumeMounts:
        - name: ca-cert
          mountPath: /ca
          readOnly: true
        - name: docker-certs
          mountPath: /host/etc/docker/certs.d
        - name: containerd-certs
          mountPath: /host/etc/containerd/certs.d
        securityContext:
          privileged: true
      volumes:
      - name: ca-cert
        secret:
          secretName: registry-ca
      - name: docker-certs
        hostPath:
          path: /etc/docker/certs.d
          type: DirectoryOrCreate
      - name: containerd-certs
        hostPath:
          path: /etc/containerd/certs.d
          type: DirectoryOrCreate
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
{{- end }}
