apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "registry.fullname" . }}-allow-all
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "registry.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - fromEndpoints:
      - {}  # Allow from all pods in the cluster
      toPorts:
      - ports:
        - port: "5000"
          protocol: TCP
  egress:
    - toEndpoints:
      - {}  # Allow to all endpoints
---
# Also create a standard NetworkPolicy for compatibility
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "registry.fullname" . }}-allow-all
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "registry.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}  # Allow all ingress traffic
  egress:
    - {}  # Allow all egress traffic