{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: ca-certificate
type: Opaque
data:
  ca.crt: {{ .Values.tls.caCert | b64enc }}
{{- end }}