nameOverride: "container-registry"
fullnameOverride: "container-registry"

replicaCount: 1

image:
  repository: registry
  tag: "2.8.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

# Persistent storage using CSI storage class
persistence:
  enabled: true
  storageClass: "csi-hostpath-sc"
  size: 10Gi
  accessMode: ReadWriteOnce

# Security context for proper permissions
securityContext:
  runAsUser: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  fsGroup: 65534

# Registry configuration
config:
  # HTTP configuration (no TLS for internal use)
  http:
    addr: ":5000"
    debug:
      addr: ":5001"
      prometheus:
        enabled: true
        path: "/metrics"
  
  # Storage configuration
  storage:
    filesystem:
      rootdirectory: /var/lib/registry
  
  # Health check configuration
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Health probes
readinessProbe:
  httpGet:
    path: /v2/
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /v2/
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 30